apiVersion: v1
kind: ConfigMap
metadata:
  name: apply-replacements-config
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    app.kubernetes.io/name: backstage
data:
  spec:
    serviceAccountName: backstage-webui-sa
    containers:
    - name: backstage
      image: gcr.io/kpt-dev/kpt-backstage-plugins/backstage-plugin-cad:v0.1.3
      ports:
      - name: http
        containerPort: 7007
      env:
      - name: CAD_AUTH_PROVDER
        value: current-context
      - name: CAD_GITOPS_DELIVERY_TOOL
        value: none
      - name: CAD_RESOURCES_NAMESPACE
        value: default
