apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: apply-replacements
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    app.kubernetes.io/name: backstage
replacements:
- source:
    kind: ConfigMap
    name: apply-replacements-config
    fieldPath: data.spec
  targets:
  - select:
      kind: Deployment
      name: backstage
    fieldPaths:
    - spec.template.spec
    options:
      create: true
