FROM us-central1-docker.pkg.dev/cloud-workstations-images/predefined/code-oss:latest

ENV DEBIAN_FRONTEND=noninteractive

COPY demo-root-sync.yaml /demo/
COPY 200_install-demo.sh /etc/workstation-startup.d/
